### ISSUE TITLE
404 error / missing template / redmine 2.4

### ISSUE THREAD

**Issue by david-strejc** [gatATAC/redmine_startpage#9]
Hi,

when I tried to configure your plugin redmine says:

  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 26.5ms (Views: 16.7ms | ActiveRecord: 0.3ms)
Started GET "/settings/plugin/redmine_startpage" for 109.233.71.242 at Fri Dec 27 16:21:21 +0100 2013
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_startpage"}
  Current user: david.strejc (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (2.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 26.9ms (Views: 19.5ms | ActiveRecord: 0.4ms)

What am I doing wrong?

**Comment by abonyir** [comment]
> Hi, sorry for the delay, still with baby's health problems + car problems (what a 2014 for me!!!). But happy as none of them is a important problem.
> 
> I have made some tests. I think the problem can be because you downloaded and extracted the plugin into the plugin directory and did not rename the resulting directory. Github adds a suffix to the plugin. I have seen that if you download it as zip in the github's plugin main page it extracts as 'redmine_startpage-master', and if you dowload the 0.0.3 tar.gz release it names it as redmine_startpage-0.0.3.
> 
> The plugins tries to find the settings page at http://localhost:3000/settings/plugin/redmine_startpage and probably redmine is publishing the settings page at http://localhost:3000/settings/plugin/redmine_startpage-0.0.3 or something similar, or directly does not publish it.
> 
> For me, this have solved the situation:
> 
> > mv redmine_startpage-0.0.3 redmine_startpage
> 
> After doing it, you will need to restart your redmine server, cause probably you are executing it in production mode and the route system (or whatever, I'm not an expert) will need to be restarted.
> 
> Please tell me if this solved your problem. I will update the readme to introduce a note so nobody will be in the same situation.
> 
> Best regards and happy 2014!
> 
> Tx.

Big thanks for the plugin renaming idea. Solved my issue with another plugin:)
